create table ods_sg_device(
    `id` bigint comment'',
    `uid` varchar(40) comment'设备uid',
    `uid_reverse` varchar(40) comment'反向索引',
    `org_code` varchar(30) comment'组织Code，左like匹配表示归自己，等于自己表示未划拨，不等于表示已经划拨',
    `model` varchar(60) comment'型号',
    `manufacturer` varchar(60) comment'厂家',
    `camera_sn` varchar(60) comment'包装码',
    `camera_type` varchar(10) comment'设备类型',
    `equip_admin` varchar(20) comment'设备用户名',
    `equip_pass` varchar(20) comment'设备密码',
    `device_server` varchar(50) comment'设备DDNS服务器',
    `alarm_server` varchar(50) comment'报警服务器',
    `connect_type` varchar(10) comment'连接方式',
    `trade_id` bigint comment'行业ID',
    `bind_user_id` bigint comment'绑定的用户id',
    `bind_time` bigint comment'绑定时间',
    `is_share` tinyint comment'是否同意分享，0不同意分享，1同意分享',
    `firmware_version` varchar(60) comment'固件版本号',
    `gmt_create` bigint comment'创建时间',
    `gmt_modify` bigint comment'修改时间',
    `plan_id` bigint comment'new ->升级任务计划Id',
    `plan_status` tinyint comment'new ->升级任务状态(0:无状态 1:升级成功 -1:升级失败，2:待下发 3下发失败 4下发成功 5下载成功 6下发中)',
    `issued_server` varchar(200) comment'new-> 服务器下发地址',
    `plan_retry_size` int comment'new->升级任务-重试次数',
    `plan_modify_time` bigint comment'new->状态变更时间',
    `black` tinyint comment'是否是黑名单 0:非 1:是',
    `cloud_server` varchar(50) comment'云存网关',
    `ddns_status` tinyint(1) comment'ddns状态',
    `ddns_status_time` bigint  comment'ddns状态更新时间',
    `is_need_card` tinyint comment'是否需要绑卡  1 需要 0 不需要',
    `default_name` varchar(20) comment'设备默认名称',
    `iccid` varchar(40) comment'iccid',
    `imei` varchar(40) comment'imei',
    `assign_time` bigint comment'设备分配时间',
    `card_org` varchar(30) comment'卡商组织code',
    `card_status` bigint comment'卡状态',
    `external_model` varchar(60) comment'外部型号',
    `ty_id` varchar(255) comment'涂鸦id',
    `ty_code` varchar(255) comment'涂鸦code',
    `pid` varchar(255) comment'涂鸦pid',
    `kcp_port` int comment'kcp端口',
    `model_type` varchar(50) comment'',
    `model_version` varchar(50) comment'',
    `profit` tinyint(1) comment'是否分润',
    `capability` text comment'能力集',
    `capability_key` varchar(32) comment'能力集md5',
    `enable` tinyint  comment'是否启用 1 启用 0',
    `contract_op_username` varchar(50) comment'导入合约机操作人',
    `contract_op_time` bigint comment'导入合约机操作时间',
    `recycle_time` bigint comment'回收操作时间',
    `promo_type` int comment'促销类型',
    `own_user_id` bigint comment'拥有者',
    `own_time` bigint comment'拥有时间',
    `is_produce` tinyint comment'是否已生产',
    `channel` varchar(60) comment'渠道',
    `produce_time` bigint comment'生产时间',
    `is_direct` tinyint comment'是否定向设备',
    `direct_op_username` varchar(50) comment'定向设备操作人',
    `direct_op_time` bigint comment'定向设备操作时间',
    `ip_operator` int comment'IP 运营商',
    `city_id` int comment'地区',
    `advert_id` int comment'广告策略id',
    `province_id` bigint comment'省',
    `country_id` bigint comment'国家',
    `merchant_code` varchar(255) comment'所属集群商户',
    `last_timer` bigint comment'代理商、渠道商最后分配时间',
    `country_code` varchar(32) comment'国家编码',
    `country_name` varchar(32) comment'国家名称',
    `continent_code` varchar(32) comment'洲际编码',
    `continent_name` varchar(32) comment'洲际名称',
    `ip` varchar(64) comment'ip',
    `interpolation` tinyint comment'设备插值 0未开启 1已开启',
    `stream_type` tinyint comment'码流类型:1主码流；2子码流',
    `sd_status` int comment'sd状态： 无卡=0 卡正常=1 卡未格式化或者卡异常=2 卡格式化中=3 卡已满=4',
    `sys_insert_time` DATETIME COMMENT '数据同步入库时间' DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
)comment'设备表';