CREATE TABLE `ods_eu_app_user` (
  `id` bigint COMMENT '主键ID',
  `username` varchar(50) COMMENT '账号（手机号）',
  `password` varchar(300) COMMENT '密码',
  `nickname` varchar(50) COMMENT '昵称',
  `app` int COMMENT '所属app',
  `sex` tinyint COMMENT '性别1男2女0未知',
  `address` varchar(300) COMMENT '地址',
  `reg_time` bigint COMMENT '注册时间戳',
  `bind_num` int COMMENT '绑定设备数',
  `gmt_modify` bigint COMMENT '更新时间戳',
  `wx_id` varchar(50) COMMENT 'wx openid',
  `wx_name` varchar(50) COMMENT '微信昵称',
  `apple_sub` varchar(50) COMMENT '苹果sub账号',
  `app_version` varchar(50) COMMENT '用户登录设备版本号',
  `platform` varchar(20) COMMENT '用户登录设备',
  `app_salt` bigint COMMENT '用户登录签名盐值',
  `ty_pass` varchar(255) COMMENT '涂鸦密码',
  `is_delete` tinyint COMMENT '是否删除 0未删1已删',
  `advert_status` int COMMENT '0 全广告 1 全关 2 限量广告 3 新用户广告',
  `region` varchar(255) COMMENT '用户所属区域',
  `register_type` int COMMENT '注册方式 1、手机号 2、邮箱',
  `token` varchar(500) COMMENT 'app登录最新token值',
  `status` int COMMENT '状态 1、正常 2、未验证',
  `active_time` bigint COMMENT '最后活跃时间戳',
  `advert_time` bigint COMMENT '广告下次开启时间戳',
  `advert_type` int COMMENT '广告操作类型 1平台 2用户',
  `app_name` varchar(50) COMMENT '用户登录app名称',
  `eye_care` int COMMENT '护眼模式 1开 0 关',
  `cloud_record_speed` int COMMENT '云录像加速播放 1 加速 0不加速',
  `advert_user_name` varchar(50) COMMENT '广告状态修改人',
  `is_bind_device` tinyint COMMENT '是否绑定过设备 1绑定过 0没有，默认0',
  `google_sub` varchar(64) COMMENT 'google sub账号标识',
  `user_update_policy` tinyint COMMENT '用户操作广告开关：0关 1开',
  `calling_code` int COMMENT '国际区号',
  `country_name` varchar(32) COMMENT '国家',
  `country_code` varchar(32) COMMENT '国家编码',
  `sys_insert_time` DATETIME COMMENT '数据同步入库时间' DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY (`id`)
)COMMENT='用户信息表'
;