CREATE TABLE `ods_eu_cloud_order` (
    `id` varchar(100) comment'',
    `uid` varchar(40) comment'设备id',
    `package_id` bigint comment'套餐id',
    `order_time` bigint comment'下单时间',
    `price` decimal(10,2) comment'订单金额',
    `is_pay` int comment'订单状态  0 未支付 1 已支付  2 支付取消',
    `pay_type` int comment'支付方式 1 微信',
    `pay_time` bigint comment'支付时间',
    `trans_no` varchar(255) comment'对应付款方订单的编号',
    `user_id` bigint comment'用户id',
    `is_delete` tinyint comment'',
    `create_time` bigint comment'',
    `modify_time` bigint comment'',
    `package_name` varchar(255) comment'套餐名称',
    `app_id` int comment'所属app 1 爱看云 2 艾尔曼',
    `type` int comment'来源0 平台 1中亿',
    `policy` int comment'云存策略 1 7天  2 14天 3 30天',
    `record_type` int comment'录像类型 1 全天录像 2 事件录像',
    `package_month` int comment'套餐月数',
    `package_day` float comment'套餐天数',
    `order_flag` int comment'施工状态',
    `order_start_time` bigint comment'订单生效开始时间',
    `order_end_time` bigint comment'订单失效结束时间',
    `order_status` int comment'订单状态 0待生效 1已生效 -1 已结束',
    `left_day` int comment'订单剩余天数',
    `is_agreement` int comment'是否协议支付 0非签约订单  1签约订单',
    `refund_status` int comment'退款状态',
    `refund_desc` text comment'退款说明',
    `refund_file_path` varchar(255) comment'退款图片',
    `refund_amount` decimal(10,2) comment'退款余额',
    `currency` varchar(255) comment'币种',
    `refund_time` bigint comment'退款时间',
    `profit_status` tinyint(1) comment'是否分润',
    `profit_refund` tinyint(1) comment'分润退款',
    `refund_receipt_file_path` varchar(255) comment'退款完成水单',
    `refund_bank_account` varchar(255) comment'退款银行账号',
    `refund_opening_bank` varchar(255) comment'退款开户行',
    `refund_bank_account_name` varchar(255) comment'退款银行户名',
    `refund_type` int comment'退款方式 1原路返回 2财务打款',
    `refund_complete_time` bigint comment'退款完成时间',
    `refund_check_time` bigint comment'退款审核时间',
    `refund_username` varchar(50) comment'退款人',
    `refund_check_username` varchar(50) comment'退款审核人',
    `refund_complete_username` varchar(50) comment'退款完成人',
    `deal_time` bigint comment'提醒处理时间',
    `curr_org_code` varchar(30) comment'当前设备所属代理',
    `curr_manufacturer_code` varchar(60) comment'当前设备所属厂家',
    `org_profit` decimal(10,2) comment'代理分润',
    `manufacturer_profit` decimal(10,2) comment'工厂分润',
    `device_package_id` bigint comment'自带套餐id',
    `curr_channel_code` varchar(60) comment'当前设备所属渠道',
    `channel_profit` decimal(10,2) comment'渠道分润',
    `package_type` int comment'套餐类型',
    `order_type` int comment'订单类型  1 主订单 2 辅（升级）订单',
    `act_policy` int comment'主实际辅升级前',
    `act_record_type` int comment'主实际辅升级前',
    `upgrade_order_id` varchar(255) comment'辅订单配套主订单id',
    `cloud_card_package_id` bigint comment'云存卡设备id',
    `donor_name` varchar(50) comment'赠送人姓名',
    `pay_sku_id` int comment'sku表对应的id',
    `check_status` tinyint comment'海外支付的检验/确认/捕获状态 0，未校验，1 已校验',
    `is_sandbox` int comment'是否沙箱订单  1：是，0：否',
    `last_timer` timestamp comment'',
    `discount` int comment'折扣',
    `order_no` varchar(100) comment'订单编号',
    `pay_order_no` varchar(100) comment'支付服务业务订单号',
    `channel_code` varchar(32) comment'支付渠道编码',
    `region_code` varchar(32) comment'支付地区',
    `out_refund_no` varchar(100) comment'支付服务退款业务订单号',
    `pay_method` varchar(64) comment'支付方法',
    `description` varchar(500) comment'赠送备注',
    `biz_type` int comment'业务大类(1：云存，2：免广告，3：AI)',
    `bind_order_id` varchar(500) comment'绑定套餐订单ID',
    `bind_type` int comment'绑定类型(0：未绑定，1：主订单，2：被绑定订单)',
    `ext_param` json comment'扩展参数(json格式)',
    `sys_insert_time` DATETIME COMMENT '数据同步入库时间' DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
)COMMENT='云存订单'
;